#!/usr/bin/env python3
"""Generates a vocabulary-specific document JSON Schema.

Takes the official document schema and specializes its node definition to
one vocabulary: component types become an enum, each component's properties
get typed value schemas (literal or $expr wrapper), event names constrain
`on`, and childless components reject `children`. Producers commit the
output next to their documents; every JSON-Schema-aware editor and CI
validator then flags mistakes at authoring time, before the gate ever runs.

    python3 tools/generate_document_schema.py vocabulary.json --out documents.schema.json

Deterministic: same artifact, same bytes. The gate remains the source of
truth; this schema is the authoring-time approximation of it (expression
result types, action capability, and cross-checks stay gate-only). This is
the same specialization the playground applies live to its document editor.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def literal_schema(descriptor):
    if isinstance(descriptor, str):
        optional = descriptor.endswith("?")
        kind = descriptor.rstrip("?")
        base = {"bool": {"type": "boolean"},
                "int": {"type": "integer"},
                "double": {"type": "number"}}.get(kind, {"type": "string"})
        return {"anyOf": [base, {"type": "null"}]} if optional else base
    if isinstance(descriptor, dict) and "enum" in descriptor:
        base = {"enum": sorted(descriptor["enum"])}
        if descriptor.get("optional"):
            return {"anyOf": [base, {"type": "null"}]}
        return base
    if isinstance(descriptor, dict) and "array" in descriptor:
        return {"type": "array", "items": literal_schema(descriptor["array"])}
    return {"type": "object"}


def value_schema(descriptor):
    return {
        "anyOf": [
            literal_schema(descriptor),
            {
                "type": "object",
                "required": ["$expr"],
                "properties": {"$expr": {"type": "string", "minLength": 1}},
                "additionalProperties": False
            }
        ]
    }


def specialize(document_schema, vocabulary):
    schema = json.loads(json.dumps(document_schema))
    schema.pop("$id", None)
    schema["title"] = (f"Milano documents for vocabulary "
                       f"{vocabulary['name']}@{vocabulary['version']}")
    schema["description"] = (
        "Generated by generate_document_schema.py; authoring-time validation "
        "specialized to one vocabulary. The gate remains the source of truth.")

    components = vocabulary.get("components", {})
    if not components:
        return schema

    per_component = []
    for name in sorted(components):
        component = components[name]
        declared = component.get("properties", {})
        events = sorted(component.get("events", {}))
        constraints = {
            "properties": {
                "type": "object",
                "propertyNames": {"enum": sorted(declared)},
                "properties": {
                    prop: value_schema(declared[prop]) for prop in sorted(declared)
                }
            },
            "on": {
                "type": "object",
                "propertyNames": {"enum": events}
            }
        }
        if not component.get("children"):
            constraints["children"] = {"type": "array", "maxItems": 0}
        per_component.append({
            "if": {"properties": {"type": {"const": name}}},
            "then": {"properties": constraints}
        })

    # The $repeat construct (contract 2.0) belongs to every vocabulary: its
    # own keys are required, a component's keys are not its to carry.
    per_component.append({
        "if": {"properties": {"type": {"const": "$repeat"}}},
        "then": {
            "required": ["items", "as", "children"],
            "properties": {
                "properties": {"type": "object", "maxProperties": 0},
                "on": {"type": "object", "maxProperties": 0}
            }
        }
    })

    # The $if construct (contract 2.1), the same way: its own keys are
    # required, and it carries none of a component's.
    per_component.append({
        "if": {"properties": {"type": {"const": "$if"}}},
        "then": {
            "required": ["condition", "then"],
            "properties": {
                "properties": {"type": "object", "maxProperties": 0},
                "on": {"type": "object", "maxProperties": 0}
            }
        }
    })

    # The $switch construct (contract 2.1), the same way.
    per_component.append({
        "if": {"properties": {"type": {"const": "$switch"}}},
        "then": {
            "required": ["subject", "cases"],
            "properties": {
                "properties": {"type": "object", "maxProperties": 0},
                "on": {"type": "object", "maxProperties": 0}
            }
        }
    })

    node = schema["$defs"]["node"]
    node["properties"]["type"] = {"enum": sorted(components) + ["$if", "$repeat", "$switch"]}
    node["allOf"] = per_component
    return schema


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vocabulary", help="path to the vocabulary artifact")
    parser.add_argument("--out", required=True, help="output schema file")
    args = parser.parse_args()

    vocabulary = json.loads(Path(args.vocabulary).read_text())
    document_schema = json.loads((ROOT / "schemas" / "document.schema.json").read_text())
    schema = specialize(document_schema, vocabulary)
    with open(args.out, "w") as handle:
        json.dump(schema, handle, indent=2)
        handle.write("\n")
    print(f"generated {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
